bundler_args: --without benchmark:site:development
script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.5.1
  - &ruby2 2.4.4
  - &ruby3 2.3.7
  - &jruby jruby-9.1.16.0

matrix:
  include:
    - rvm: *ruby1
      env: TEST_SUITE=fmt
    - rvm: *ruby1
      env: TEST_SUITE=default-site
  exclude:
    - rvm: *jruby
      env: TEST_SUITE=cucumber

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber

before_install:
  - gem update --system
  - gem install bundler --version 1.16.2
